FROM aidamian/base_edge_node_arm64_cpu:latest

# first we copy the get_info script to the root folder
WORKDIR /
COPY get_node_info /usr/local/bin/get_node_info
RUN chmod +x /usr/local/bin/get_node_info


WORKDIR /edge_node

COPY  . /edge_node

# set a generic env variable 
ENV AINODE_DOCKER=Yes

# set a generic env variable 
ENV AINODE_DOCKER_SOURCE=main

# set default Execution Engine id
ENV EE_ID=E2dkr

# also can use EE_DEVICE to define target such as cuda:0 or cuda:1 instead of cpu
# althouh this is not recommended as it should be in .env file
# ENV EE_DEVICE=cuda:0

# Temporary fix:
ENV AINODE_ENV=$AI_ENV
ENV AINODE_ENV_VER=$AI_ENV_VER

# configure default config_startup file
ENV EE_CONFIG=.config_startup.json

ENV EE_ETH_ENABLED=true


ENV TZ=Europe/Bucharest
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir --no-deps naeural-core

CMD ["/usr/bin/python3","device.py"]
