FROM aidamian/base_edge_node_arm64_cpu:latest

WORKDIR /exe_eng

COPY  . /exe_eng

# set a generic env variable 
ENV AIXP_DOCKER Yes

# set a generic env variable 
ENV AIXP_DOCKER_SOURCE main

# set default Execution Engine id
ENV EE_ID E2dkr

# also can use EE_DEVICE to define target such as cuda:0 or cuda:1 instead of cpu
# althouh this is not recommended as it should be in .env file
# ENV EE_DEVICE cuda:0

# Temporary fix:
ENV AIXP_ENV $AI_ENV
ENV AIXP_ENV_VER $AI_ENV_VER

# configure default config_startup file
ENV EE_CONFIG .config_startup.json

ENV TZ=Europe/Bucharest
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

## The following line should NOT be moved to based as it should always be updated
RUN pip install --no-cache-dir kmonitor PyE2 decentra-vision
## END do not move

CMD ["/usr/bin/python3","device.py"]
