FROM aidamian/base_edge_node_arm64_tegra:latest


COPY ./cmds /usr/local/bin/
RUN chmod +x /usr/local/bin/*


WORKDIR /edge_node
COPY . .
RUN rm -rf /edge_node/cmds

#### TO BE REMOVED AND TESTED !!!
ENV TZ=Europe/Bucharest
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#### END TO BE REMOVED


# set a generic env variable 
ENV AINODE_DOCKER=Yes

# set a generic env variable
ENV AINODE_DOCKER_SOURCE=develop

# set default Execution Engine id
ENV EE_ID=E2dkr

ENV AINODE_ENV=$AI_ENV
ENV AINODE_ENV_VER=$AI_ENV_VER

ENV EE_ETH_ENABLED=true
ENV EE_HB_CONTAINS_PIPELINES=0
ENV EE_HB_CONTAINS_ACTIVE_PLUGINS=1
ENV EE_EPOCH_MANAGER_DEBUG=1


# also can use EE_DEVICE to define target such as cuda:0 or cuda:1 instead of cpu
ENV EE_DEVICE=cuda:0

# configure default config_startup file
ENV EE_CONFIG=.config_startup.json

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir --no-deps naeural-core

CMD ["python3","device.py"]
