FROM aidamian/base_edge_node_arm64_tegra:latest

# first we copy the get_info script to the root folder
WORKDIR /
COPY get_node_info /usr/local/bin/get_node_info
RUN chmod +x /usr/local/bin/get_node_info

COPY add_allowed /usr/local/bin/add_allowed
RUN chmod +x /usr/local/bin/add_allowed



WORKDIR /edge_node

COPY  . /edge_node

# Set a default value for the TZ environment variable
ENV TZ=Europe/Bucharest
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# set a generic env variable 
ENV AINODE_DOCKER=Yes

# set a generic env variable
ENV AINODE_DOCKER_SOURCE=develop

# set default Execution Engine id
ENV EE_ID=E2dkr

ENV AINODE_ENV=$AI_ENV
ENV AINODE_ENV_VER=$AI_ENV_VER

ENV EE_ETH_ENABLED=true


# also can use EE_DEVICE to define target such as cuda:0 or cuda:1 instead of cpu
ENV EE_DEVICE=cuda:0

# configure default config_startup file
ENV EE_CONFIG=.config_startup.json

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir --no-deps naeural-core

CMD ["python3","device.py"]
