FROM aidamian/base_edge_node_arm64_cpu:latest

WORKDIR /edge_node

COPY  . /edge_node

# set a generic env variable 
ENV AINODE_DOCKER Yes

# set a generic env variable 
ENV AINODE_DOCKER_SOURCE develop

# set default Execution Engine id
ENV EE_ID E2dkr

# also can use EE_DEVICE to define target such as cuda:0 or cuda:1 instead of cpu
# althouh this is not recommended as it should be in .env file
# ENV EE_DEVICE cuda:0

# Temporary fix:
ENV AINODE_ENV $AI_ENV
ENV AINODE_ENV_VER $AI_ENV_VER

# configure default config_startup file
ENV EE_CONFIG .config_startup.json

ENV TZ=Europe/Bucharest
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

## The following line should NOT be moved to based as it should always be updated
RUN pip install --no-cache-dir kmonitor naeural_client decentra-vision
## END do not move

RUN pip install --no-cache-dir --no-deps naeural-core

CMD ["/usr/bin/python3","device.py"]
