##
## No need for Watchtower in this case, as we are using the (local) local_edge_node image
##
services:
  naeural_01:
    image: local_edge_node
    container_name: naeural_01
    restart: always
    volumes:
      - naeural_01:/edge_node/_local_cache
       

  naeural_02:
    image: local_edge_node
    container_name: naeural_02
    restart: always
    volumes:
      - naeural_02:/edge_node/_local_cache
         

  naeural_03:
    image: local_edge_node
    container_name: naeural_03
    restart: always
    volumes:
      - naeural_03:/edge_node/_local_cache
        

volumes:
  naeural_01:
  naeural_02:
  naeural_03:
