##
## No need for Watchtower in this case, as we are using the (local) local_edge_node image
##


services:
  naeural_01:
    image: local_edge_node
    container_name: naeural_01
    restart: always
    environment:
      EE_ID: ${EE_ID_01?You must set the EE_ID_01 environment variable}
    env_file: .env
    volumes:
      - naeural_01:/edge_node/_local_cache
       

  naeural_02:
    image: local_edge_node
    container_name: naeural_02
    restart: always
    environment:
      EE_ID: ${EE_ID_02?You must set the EE_ID_02 environment variable}
    env_file: .env
    volumes:
      - naeural_02:/edge_node/_local_cache
         

  naeural_03:
    image: local_edge_node
    container_name: naeural_03
    restart: always
    environment:
      EE_ID: ${EE_ID_03?You must set the EE_ID_03 environment variable3}
    env_file: .env
    volumes:
      - naeural_03:/edge_node/_local_cache
        

volumes:
  naeural_01:
  naeural_02:
  naeural_03:
