
services:
  naeural_01:
    image: naeural/edge_node:develop
    container_name: naeural_01
    restart: always
    environment:
      EE_ID: ${EE_ID_01?You must set the EE_ID_01 environment variable}
    env_file: .env
    volumes:
      - naeural_01:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  naeural_02:
    image: naeural/edge_node:develop
    container_name: naeural_02
    restart: always
    environment:
      EE_ID: ${EE_ID_02?You must set the EE_ID_02 environment variable}
    env_file: .env
    volumes:
      - naeural_02:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  naeural_03:
    image: naeural/edge_node:develop
    container_name: naeural_03
    restart: always
    environment:
      EE_ID: ${EE_ID_03?You must set the EE_ID_03 environment variable3}
    env_file: .env
    volumes:
      - naeural_03:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          


  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60 # Check every 1 minute
      - WATCHTOWER_CHECK_NEW_IMAGES=true      
      - WATCHTOWER_LABEL_ENABLE=true        

volumes:
  naeural_01:
  naeural_02:
  naeural_03:
