#!/bin/bash
###
### This script will dump the local info JSON of the edge node
###
FILE=/edge_node/_local_cache/_data/local_info.json

if [ ! -f "$FILE" ]; then
    echo "Error: $FILE does not exist"
    exit 1
fi

# `cat` is called this way in order to have a newline after the file content
echo "`cat $FILE`"