#!/bin/bash
###
### This script gets the startup config of the edge node
###
FILE=/edge_node/_local_cache/config_startup.json

if [ ! -f "$FILE" ]; then
    echo "Error: $FILE does not exist"
    exit 1
fi

cat $FILE
