#!/bin/bash
###
### This script displays the contents of the e2.pem file used for edge node authentication
### If the file doesn't exist, it will display an appropriate message
###
FILE=/edge_node/_local_cache/_data/e2.pem

if [ -f "$FILE" ]; then
    cat "$FILE"
    echo -e "\nSuccessfully displayed $FILE"
else
    echo "File $FILE does not exist"
fi 