#!/bin/bash
###
### This script gets config app
###
FILE=/edge_node/_local_cache/_data/box_configuration/config_app.txt

if [ ! -f "$FILE" ]; then
    echo "Error: $FILE does not exist"
    exit 1
fi

cat $FILE
