#!/bin/bash
###
### This script gets all address from the list of authorized addresses
###
FILE=/edge_node/_local_cache/authorized_addrs

if [ ! -f "$FILE" ]; then
    echo "Error: $FILE does not exist"
    exit 1
fi

cat $FILE
