# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build develop image

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      ## version getting and debugging

      - name: Retrieve edge node version
        id: retrieve_version
        run: |
          echo "VERSION=$(cat ver.py | grep -o "'.*'")" >> $GITHUB_ENV

      - name: Check latest naeural_core version
        id: check_core_latest_version
        run: |
          LATEST_VERSION=$(curl -s https://pypi.org/pypi/naeural-core/json | jq -r '.info.version')
          echo "LATEST_NAEURAL_CORE_VERSION=$LATEST_VERSION" >> $GITHUB_ENV          

      - name: Debug version
        run: |
          VERSION=${VERSION//\'/}
          echo "Develop version to build: '$VERSION'"
          echo "Latest naeural_core version on PyPI: '$LATEST_NAEURAL_CORE_VERSION'"
        env:
          VERSION: ${{ env.VERSION }}
          LATEST_NAEURAL_CORE_VERSION: ${{ env.LATEST_NAEURAL_CORE_VERSION }}

      ## End of version getting and debugging

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "naeural/naeural-builder"

      - name: Cleanup space
        run: |
              echo "===========docker buildx du ==================="
              docker buildx du
              echo "===========docker buildx prune -f. Add -af if any other space issues. ============"
              docker buildx prune -f
              echo "===========docker buildx du ================="
              docker buildx du
              echo "========================================"
    

      - name: Build and push Amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_dev
          push: true
          # tags: "naeural/edge_node:develop"
          tags: |
                naeural/edge_node:develop
                naeural/edge_node:testnet
